server:
  port: 6001
spring:
  application:
    name: leadnews-admin-gateway
  cloud:
    nacos:
      server-addr: 192.168.211.128:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedHeaders: "*"
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 后台管理
        - id: admin
          uri: lb://leadnews-admin
          predicates:
            - Path=/admin/**
          filters:
            # StripPrefix 去掉路径中的一个前缀 /admin
            # http://localhost:6001/admin/login/in  转发后的路径应该是 /admin/login/in
            # 经过去前缀后： /admin/login/in => /login/in
            - StripPrefix= 1